#!/usr/bin/env python3
"""Publishing queue for APPROVED episodes: 3 Shorts per day at fixed US (New York) times.

Usage (cd /root/video-engine):
  ./venv/bin/python generators/publishing/publish_queue.py plan [--start YYYY-MM-DD]   # assign slots, write PUBLISH_QUEUE.md
  ./venv/bin/python generators/publishing/publish_queue.py show
  ./venv/bin/python generators/publishing/publish_queue.py upload --confirm            # ONLY on the user's explicit instruction

Each queued episode is uploaded as private with YouTube `publishAt`; YouTube itself makes it public at the
slot time (no cron on our side). Slots are in America/New_York, so US daylight-saving changes are automatic.
Only APPROVED episodes without a youtube_url are queued; order = episode number.
"""
import argparse
import datetime as dt
import json
import os
import sys
from zoneinfo import ZoneInfo

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(HERE, "..", "physics_2d"))
sys.path.insert(0, HERE)
import episodes  # noqa: E402

NY = ZoneInfo("America/New_York")
WIB = ZoneInfo("Asia/Jakarta")
SLOTS = [(11, 0), (15, 0), (19, 0)]      # ET: late morning, after school, evening prime time (BLUEPRINT 10)
QUEUE_FILE = f"{episodes.BASE}/renders/megawheel_arena/PUBLISH_QUEUE.json"
QUEUE_MD = f"{episodes.BASE}/renders/megawheel_arena/PUBLISH_QUEUE.md"
CATEGORY_FILM_ANIMATION = "1"


def load():
    if os.path.exists(QUEUE_FILE):
        with open(QUEUE_FILE) as fh:
            return json.load(fh)
    return {"items": []}


def save(q):
    with open(QUEUE_FILE, "w") as fh:
        json.dump(q, fh, indent=1)
    lines = ["# PUBLISH_QUEUE â€” MegaWheel Arena", "",
             "Auto-generated by `publish_queue.py`. Times: New York (ET) = what US viewers see; WIB for reference.", "",
             "| Ep | Video | Publish (ET) | Publish (WIB) | Status | URL |", "|---|---|---|---|---|---|"]
    for it in q["items"]:
        et = dt.datetime.fromisoformat(it["publish_at_utc"].replace("Z", "+00:00"))
        lines.append(f"| {it['episode']} | {it['video_id']} | {et.astimezone(NY):%a %Y-%m-%d %H:%M} | "
                     f"{et.astimezone(WIB):%a %Y-%m-%d %H:%M} | {it['status']} | {it.get('url', '')} |")
    with open(QUEUE_MD, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def next_slots(start_day, taken, now_utc):
    day = start_day
    while True:
        for h, m in SLOTS:
            t = dt.datetime(day.year, day.month, day.day, h, m, tzinfo=NY).astimezone(dt.timezone.utc)
            # YouTube needs publishAt in the future; keep a 2 h margin for the upload itself
            if t > now_utc + dt.timedelta(hours=2) and t not in taken:
                yield t
        day += dt.timedelta(days=1)


def plan(start):
    q = load()
    queued = {it["episode"] for it in q["items"]}
    taken = {dt.datetime.fromisoformat(it["publish_at_utc"].replace("Z", "+00:00")) for it in q["items"]}
    todo = [e for e in episodes.episodes()
            if e.get("status") == "APPROVED" and not e.get("youtube_url") and e["episode"] not in queued]
    todo.sort(key=lambda e: e["episode"])
    now = dt.datetime.now(dt.timezone.utc)
    last = max(taken, default=None)
    start_day = start or (last.astimezone(NY).date() if last else now.astimezone(NY).date())
    gen = next_slots(start_day, taken, now)
    for e in todo:
        t = next(gen)
        q["items"].append(dict(episode=e["episode"], video_id=e["video_id"], status="QUEUED",
                               publish_at_utc=t.strftime("%Y-%m-%dT%H:%M:%SZ")))
    q["items"].sort(key=lambda it: it["publish_at_utc"])
    save(q)
    show()


def show():
    with open(QUEUE_MD) as fh:
        print(fh.read())


def upload():
    from core.youtube_uploader import YouTubeUploader
    q = load()
    uploader = YouTubeUploader()
    if not uploader.is_authenticated():
        sys.exit("[queue] STOP: YouTube belum terotentikasi (jalankan auth_youtube.py).")
    now = dt.datetime.now(dt.timezone.utc)
    for it in q["items"]:
        if it["status"] != "QUEUED":
            continue
        t = dt.datetime.fromisoformat(it["publish_at_utc"].replace("Z", "+00:00"))
        if t < now + dt.timedelta(minutes=30):
            print(f"[queue] SKIP Ep. {it['episode']}: slot {it['publish_at_utc']} sudah lewat -> jalankan plan ulang")
            continue
        e = episodes.by_episode(it["episode"])
        if not e or e.get("status") != "APPROVED" or e.get("youtube_url"):
            print(f"[queue] SKIP Ep. {it['episode']}: status {e and e.get('status')} / sudah ada URL")
            continue
        folder = f"{episodes.BASE}/{e['folder']}"
        with open(f"{folder}/{e['video_id']}.json") as fh:
            m = json.load(fh)
        print(f"[queue] Ep. {it['episode']} | {m['title']} | publishAt {it['publish_at_utc']}", flush=True)
        res = uploader.upload_shorts(video_path=f"{folder}/{e['video_id']}.mp4", title=m["title"],
                                     description=m["description"], tags=m["tags"],
                                     category_id=CATEGORY_FILM_ANIMATION, privacy_status="private",
                                     made_for_kids=False, publish_at=it["publish_at_utc"])
        it.update(status="SCHEDULED", url=res["url"])
        episodes.mark_uploaded(it["episode"], res["url"], f"scheduled {it['publish_at_utc']}")
        save(q)
        print(f"[queue] OK -> {res['url']}", flush=True)
    episodes.write_log()
    show()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["plan", "show", "upload"])
    ap.add_argument("--start", help="first publish day (New York date), default: today/after last slot")
    ap.add_argument("--confirm", action="store_true", help="required for upload (user instruction)")
    a = ap.parse_args()
    if a.cmd == "plan":
        plan(dt.date.fromisoformat(a.start) if a.start else None)
    elif a.cmd == "show":
        show()
    else:
        if not a.confirm:
            sys.exit("[queue] STOP: upload butuh --confirm (hanya atas instruksi eksplisit user).")
        upload()


if __name__ == "__main__":
    main()
