#!/usr/bin/env python3
"""Publishing queue for APPROVED episodes: 3 Shorts per day at fixed US (New York) times.

Usage (cd /root/video-engine):
  ./venv/bin/python generators/publishing/publish_queue.py plan [--start YYYY-MM-DD]   # assign slots, write PUBLISH_QUEUE.md
  ./venv/bin/python generators/publishing/publish_queue.py show
  ./venv/bin/python generators/publishing/publish_queue.py upload --confirm            # ONLY on the user's explicit instruction

Each queued episode is uploaded as private with YouTube `publishAt`; YouTube itself makes it public at the
slot time (no cron on our side). Slots are in America/New_York, so US daylight-saving changes are automatic.
Only APPROVED episodes without a youtube_url are queued; order = episode number.
"""
import argparse
import datetime as dt
import json
import os
import sys
from zoneinfo import ZoneInfo

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(HERE, "..", "physics_2d"))
sys.path.insert(0, HERE)
import episodes  # noqa: E402

NY = ZoneInfo("America/New_York")
WIB = ZoneInfo("Asia/Jakarta")
SLOTS = [(11, 0), (15, 0), (19, 0)]      # ET: late morning, after school, evening prime time (BLUEPRINT 10)
# UPLOAD RULE (user 2026-10-01, strict): 11:00 ET = CHALLENGE (2D side view) only, 15:00 ET = RACE (race25d) only,
# 19:00 ET = SMASH ARENA (smash25d) only. Saturday 19:00 ET is reserved for the weekly long episode (story15); while
# no long episode is approved, SMASH takes it. No other fallback: an empty slot stays empty and plan() warns.
# Stock standard: at least 7 days of each type queued (plan() prints PERINGATAN STOK).
RACE_SERIES = {"race25d"}
SMASH_SERIES = {"smash25d"}
LONG_SERIES = {"story15"}                 # weekly long-form series id (reserved)
WEEKLY_LONG_SLOT = (5, 19)                # Saturday (weekday 5), 19:00 ET


def slot_role(t_utc):
    et = t_utc.astimezone(NY)
    if (et.weekday(), et.hour) == WEEKLY_LONG_SLOT:
        return "long"
    return "race" if et.hour == 15 else "smash" if et.hour == 19 else "short"


def role_of(series):
    return ("race" if series in RACE_SERIES else "smash" if series in SMASH_SERIES
            else "long" if series in LONG_SERIES else "short")


SLOT_ROLES_OF = {"race": {"race"}, "smash": {"smash", "long"}, "short": {"short"}, "long": {"long"}}
PLAN_ORDER = {"race": 0, "long": 1, "smash": 2, "short": 3}   # a long episode claims Saturday 19:00 before SMASH
ROLE_NAME = {"short": "CHALLENGE (11:00 ET)", "race": "RACE race25d (15:00 ET)", "smash": "SMASH smash25d (19:00 ET)"}
STOCK_DAYS = 7


QUEUE_FILE = f"{episodes.BASE}/renders/megawheel_arena/PUBLISH_QUEUE.json"
QUEUE_MD = f"{episodes.BASE}/renders/megawheel_arena/PUBLISH_QUEUE.md"
CATEGORY_FILM_ANIMATION = "1"


def load():
    if os.path.exists(QUEUE_FILE):
        with open(QUEUE_FILE) as fh:
            return json.load(fh)
    return {"items": []}


def save(q):
    with open(QUEUE_FILE, "w") as fh:
        json.dump(q, fh, indent=1)
    lines = ["# PUBLISH_QUEUE - MegaWheel Arena", "",
             "Auto-generated by `publish_queue.py`. Times: New York (ET) = what US viewers see; WIB for reference.", "",
             "| Ep | Video | Publish (ET) | Publish (WIB) | Status | URL |", "|---|---|---|---|---|---|"]
    for it in q["items"]:
        et = dt.datetime.fromisoformat(it["publish_at_utc"].replace("Z", "+00:00"))
        lines.append(f"| {it['episode']} | {it['video_id']} | {et.astimezone(NY):%a %Y-%m-%d %H:%M} | "
                     f"{et.astimezone(WIB):%a %Y-%m-%d %H:%M} | {it['status']} | {it.get('url', '')} |")
    with open(QUEUE_MD, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    episodes.write_index()                                   # keep the agent index in sync with the queue


def next_slots(start_day, taken, now_utc, roles):
    day = start_day
    while True:
        for h, m in SLOTS:
            t = dt.datetime(day.year, day.month, day.day, h, m, tzinfo=NY).astimezone(dt.timezone.utc)
            # YouTube needs publishAt in the future; keep a 2 h margin for the upload itself
            if t > now_utc + dt.timedelta(hours=2) and t not in taken and slot_role(t) in roles:
                yield t
        day += dt.timedelta(days=1)


def plan(start):
    q = load()
    # Items already on YouTube (SCHEDULED/...) keep their slot. Every not-yet-uploaded item is re-slotted each plan,
    # in episode order per role, into the earliest free future slot OF ITS ROLE (race / short / long).
    old = {it["episode"]: it["publish_at_utc"] for it in q["items"] if it["status"] == "QUEUED"}
    q["items"] = [it for it in q["items"] if it["status"] != "QUEUED"]
    queued = {it["episode"] for it in q["items"]}
    taken = {dt.datetime.fromisoformat(it["publish_at_utc"].replace("Z", "+00:00")) for it in q["items"]}
    todo = [e for e in episodes.episodes()
            if e.get("status") == "APPROVED" and not e.get("youtube_url") and e["episode"] not in queued]
    todo.sort(key=lambda e: (PLAN_ORDER[role_of(e.get("series", ""))], e["episode"]))
    now = dt.datetime.now(dt.timezone.utc)
    start_day = start or now.astimezone(NY).date()
    gens = {r: next_slots(start_day, taken, now, SLOT_ROLES_OF[r]) for r in SLOT_ROLES_OF}
    for e in todo:
        slot = next(gens[role_of(e.get("series", ""))])
        taken.add(slot)
        t = slot.strftime("%Y-%m-%dT%H:%M:%SZ")
        if e["episode"] in old and old[e["episode"]] != t:
            print(f"[queue] Ep. {e['episode']}: slot {old[e['episode']]} -> {t}")
        q["items"].append(dict(episode=e["episode"], video_id=e["video_id"], status="QUEUED", publish_at_utc=t,
                               role=role_of(e.get("series", ""))))
    q["items"].sort(key=lambda it: it["publish_at_utc"])
    save(q)
    # stock standard: each of the next STOCK_DAYS days needs its CHALLENGE, RACE and SMASH Short
    today = now.astimezone(NY).date()
    days = [today + dt.timedelta(days=d) for d in range(1, STOCK_DAYS + 1)]
    for role in ("short", "race", "smash"):
        have = set()
        for it in q["items"]:
            t = dt.datetime.fromisoformat(it["publish_at_utc"].replace("Z", "+00:00"))
            if role_of_item(it) == role:
                have.add(t.astimezone(NY).date())
        missing = [str(d_) for d_ in days if d_ not in have]
        if missing:
            print(f"[queue] PERINGATAN STOK: belum ada {ROLE_NAME[role]} untuk {', '.join(missing)} "
                  f"-> produksi & approve lagi (standar {STOCK_DAYS} hari)")
        else:
            print(f"[queue] stok {ROLE_NAME[role]}: OK {STOCK_DAYS} hari ke depan")
    show()


def role_of_item(it):
    """Role of a queue item (older items have no 'role' field: derive it from the registry series)."""
    if it.get("role"):
        return it["role"]
    e = next((x for x in episodes.episodes() if x["episode"] == it["episode"]), {})
    return role_of(e.get("series", ""))


def show():
    with open(QUEUE_MD) as fh:
        print(fh.read())


def upload(max_n):
    """Upload up to max_n QUEUED episodes (YouTube API quota: videos.insert = 1600 of 10000 units/day)."""
    from core.youtube_uploader import YouTubeUploader
    q = load()
    done = 0
    uploader = YouTubeUploader()
    if not uploader.is_authenticated():
        sys.exit("[queue] STOP: YouTube belum terotentikasi (jalankan auth_youtube.py).")
    now = dt.datetime.now(dt.timezone.utc)
    for it in q["items"]:
        if it["status"] != "QUEUED":
            continue
        if done >= max_n:
            print(f"[queue] batas {max_n} upload per run tercapai (kuota API). Sisanya di run berikutnya.")
            break
        t = dt.datetime.fromisoformat(it["publish_at_utc"].replace("Z", "+00:00"))
        if t < now + dt.timedelta(minutes=30):
            print(f"[queue] SKIP Ep. {it['episode']}: slot {it['publish_at_utc']} sudah lewat -> jalankan plan ulang")
            continue
        e = episodes.by_episode(it["episode"])
        if not e or e.get("status") != "APPROVED" or e.get("youtube_url"):
            print(f"[queue] SKIP Ep. {it['episode']}: status {e and e.get('status')} / sudah ada URL")
            continue
        folder = f"{episodes.BASE}/{e['folder']}"
        with open(f"{folder}/{e['video_id']}.json") as fh:
            m = json.load(fh)
        print(f"[queue] Ep. {it['episode']} | {m['title']} | publishAt {it['publish_at_utc']}", flush=True)
        res = uploader.upload_shorts(video_path=f"{folder}/{e['video_id']}.mp4", title=m["title"],
                                     description=m["description"], tags=m["tags"],
                                     category_id=CATEGORY_FILM_ANIMATION, privacy_status="private",
                                     made_for_kids=False, publish_at=it["publish_at_utc"])
        it.update(status="SCHEDULED", url=res["url"])
        episodes.mark_uploaded(it["episode"], res["url"], f"scheduled {it['publish_at_utc']}")
        save(q)
        done += 1
        print(f"[queue] OK -> {res['url']}", flush=True)
    episodes.write_log()
    show()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["plan", "show", "upload"])
    ap.add_argument("--start", help="first publish day (New York date), default: today/after last slot")
    ap.add_argument("--confirm", action="store_true", help="required for upload (user instruction)")
    ap.add_argument("--max", type=int, default=5, help="max uploads per run (API quota), default 5")
    a = ap.parse_args()
    if a.cmd == "plan":
        plan(dt.date.fromisoformat(a.start) if a.start else None)
    elif a.cmd == "show":
        show()
    else:
        if not a.confirm:
            sys.exit("[queue] STOP: upload butuh --confirm (hanya atas instruksi eksplisit user).")
        upload(a.max)


if __name__ == "__main__":
    main()
